require				'rubygems'
require       'bundler'
Bundler.require(:default)

require 'sdl'
require 'logger'

#require_relative './lib/rgss'
require_relative './lib/bitmap'
require_relative './lib/color'
require_relative './lib/font'
require_relative './lib/plane'
require_relative './lib/rect'
require_relative './lib/sf_sprite'
require_relative './lib/table'
require_relative './lib/tilemap'
require_relative './lib/tone'
require_relative './lib/viewport'
require_relative './lib/window'
require_relative './lib/rgss'
require_relative './lib/audio'
require_relative './lib/graphics'
require_relative './lib/input'
require_relative './lib/rpg'
require_relative './lib/sprite'
require_relarive './lib/spriteset'
require_relative './lib/window'
require_relative './lib/interpreters'
require_relative './lib/scene'
require_relative './lib/main'
